spring.application.name=lect_B
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp
message.greeting=hello, Spring DI with @Autowired and Setter Injection!

# Week 10 DB 연동 실습 (로컬 MySQL 사용)
spring.datasource.url=jdbc:mysql://localhost:3306/springdb?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver