week05.server.port=8080
week05.server.address=localhost

week05.mail.host=smtp.lect-b.local
week05.mail.port=2525
week05.mail.timeout-seconds=30
week05.mail.credentials.username=week05-user
week05.mail.credentials.password=scope-secret
week05.mail.default-recipients[0]=teacher@lect-b.local
week05.mail.default-recipients[1]=assistant@lect-b.local
