week06.server.port=8080
week06.server.address=localhost
week06.message.greeting=hello, week06 external properties!

week06.datasource.url=jdbc:mysql://localhost:3306/lect_b_week06
week06.datasource.user-name=lectb_user
week06.datasource.password=week06_password
