DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    REGDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
