INSERT INTO MEMBER (EMAIL, PASSWORD, NAME, REGDATE) VALUES ('seed1@virus.net', '1234', 'seed1', CURRENT_TIMESTAMP);
INSERT INTO MEMBER (EMAIL, PASSWORD, NAME, REGDATE) VALUES ('seed2@virus.net', '1234', 'seed2', CURRENT_TIMESTAMP);
