# 교수님 실습 방식: static 폴더 아래 외부 설정 파일 1개만 사용

# 공통 예시
server.port=8080
server.address=localhost
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=password
logging.level.org.springframework=DEBUG

# week05: @Value
week05.server.port=8080
week05.server.address=localhost

# week05: @ConfigurationProperties(prefix = "week05.mail")
week05.mail.host=smtp.gmail.com
week05.mail.port=587
week05.mail.timeout-seconds=30
week05.mail.credentials.username=lectb_week05
week05.mail.credentials.password=week05_password
week05.mail.default-recipients[0]=student1@lectb.local
week05.mail.default-recipients[1]=student2@lectb.local

# week06: @Value
week06.server.port=8080
week06.server.address=localhost
week06.message.greeting=hello, week06 external properties!

# week06: @ConfigurationProperties(prefix = "week06.datasource")
week06.datasource.url=jdbc:mysql://localhost:3306/mydb
week06.datasource.user-name=root
week06.datasource.password=password
